title: Theme Transformer
description: The official implementation of Theme Transformer
show_downloads: false
show_arxiv: true

baseurl: "/ThemeTransformer" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://atosystem.github.io" # change this to the base hostname & protocol for your site
url_arxiv: "https://arxiv.org/abs/2111.04093"

google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: Ian Shih
image: /thumbnail-jumbo.png
twitter:
  username: yijenshih

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['demo', 'code', 'cite', 'contact']
